AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: your-first-lamda.lambda_handler  
      Runtime: python3.8
      CodeUri: s3://hyr-bucket/deployment.zip 
      Environment:
        Variables:
          TABLE_NAME: 'MyTable'
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /myendpoint
            Method: get

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/myendpoint/"
